# Generated by Django 5.1.1 on 2026-08-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='attachment_file',
            field=models.FileField(blank=True, null=True, upload_to='medical_records/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
