# Generated by Django 5.1.1 on 2026-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_user_totp_secret_user_two_factor_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pictures/'),
        ),
    ]
