# Generated by Django 5.1.1 on 2026-10-02 18:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_doctorreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, help_text='Systolic Blood Pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(260)])),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, help_text='Diastolic Blood Pressure (mmHg)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(180)])),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='Heart rate / pulse (beats per minute)', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, help_text='Blood glucose level (mg/dL)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('20.0')), django.core.validators.MaxValueValidator(Decimal('600.0'))])),
                ('glucose_context', models.CharField(choices=[('fasting', 'Fasting'), ('post_meal', 'After Meal (Post-prandial)'), ('random', 'Random'), ('bedtime', 'Bedtime')], default='random', max_length=20)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Fahrenheit (°F)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('90.0')), django.core.validators.MaxValueValidator(Decimal('110.0'))])),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, help_text='Pulse oximeter oxygen saturation (% SpO2)', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('2.0')), django.core.validators.MaxValueValidator(Decimal('350.0'))])),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('30.0')), django.core.validators.MaxValueValidator(Decimal('260.0'))])),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bmi_category', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='models.patient')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_vitals',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'recorded_at'], name='patient_vit_patient_8ad00e_idx'), models.Index(fields=['patient', 'is_deleted'], name='patient_vit_patient_3a1af3_idx')],
            },
        ),
    ]
