# Generated by Django 5.1.1 on 2026-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_patientvital'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='has_safety_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='prescription',
            name='safety_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
