# Generated by Django 5.1.1 on 2026-10-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
