export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register/',
    LOGIN: '/auth/login/',
    LOGOUT: '/auth/logout/',
    PROFILE: '/auth/profile/',
    CHANGE_PASSWORD: '/auth/change-password/',
    // Matches backend: /auth/refresh-token/ (also aliased as /auth/token/refresh/)
    REFRESH_TOKEN: '/auth/refresh-token/',
    PASSWORD_RESET: '/auth/password-reset/',
    PASSWORD_RESET_CONFIRM: '/auth/password-reset/confirm/',
    TWO_FACTOR_VERIFY: '/auth/2fa/verify/',
    TWO_FACTOR_SETUP: '/auth/2fa/setup/',
    TWO_FACTOR_ENABLE: '/auth/2fa/enable/',
    TWO_FACTOR_DISABLE: '/auth/2fa/disable/',
  },
  PATIENTS: {
    LIST: '/patients/',
    DETAIL: (id: string) => `/patients/${id}/`,
    ME: '/patients/me/',
  },
  DOCTORS: {
    LIST: '/doctors/',
    DETAIL: (id: string) => `/doctors/${id}/`,
    ME: '/doctors/me/',
    AVAILABILITY: '/doctors/me/',
  },
  APPOINTMENTS: {
    LIST: '/appointments/',
    DETAIL: (id: string) => `/appointments/${id}/`,
    CANCEL: (id: string) => `/appointments/${id}/cancel/`,
    MY: '/appointments/my/',
    SLOTS: (doctorId: string) => `/appointments/available-slots/${doctorId}/`,
    SEND_REMINDER: (id: string) => `/appointments/${id}/send-reminder/`,
    TRIGGER_BATCH_REMINDERS: '/appointments/trigger-reminders/',
  },
  BILLING: {
    LIST: '/billing/',
    DETAIL: (id: string) => `/billing/${id}/`,
    MY: '/billing/my/',
    PAY: (id: string) => `/billing/${id}/pay/`,
    PDF: (id: string) => `/billing/${id}/pdf/`,
  },
  MEDICAL_RECORDS: {
    LIST: '/medical-records/',
    DETAIL: (id: string) => `/medical-records/${id}/`,
    MY: '/medical-records/my/',
  },
  ADMIN: {
    DASHBOARD: '/admin/dashboard/',
    ANALYTICS: '/admin/analytics/',
    EXPORT_APPOINTMENTS: '/admin/export/appointments/',
    EXPORT_BILLING: '/admin/export/billing/',
    EXPORT_PATIENTS: '/admin/export/patients/',
    EXPORT_DOCTORS: '/admin/export/doctors/',
    USERS: '/admin/users/',
    USER_DETAIL: (id: string) => `/admin/users/${id}/`,
    PENDING_DOCTORS: '/admin/doctors/pending/',
    APPROVE_DOCTOR: (id: string) => `/admin/doctors/${id}/approve/`,
    VERIFY_DOCTOR: (id: string) => `/admin/doctors/${id}/verify/`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    READ: (id: string) => `/notifications/${id}/read/`,
    READ_ALL: '/notifications/read-all/',
  },
  PRESCRIPTIONS: {
    LIST: '/prescriptions/',
    DETAIL: (id: string) => `/prescriptions/${id}/`,
    MY: '/prescriptions/my/',
    REFILL: (id: string) => `/prescriptions/${id}/refill/`,
    PDF: (id: string) => `/prescriptions/${id}/pdf/`,
    CHECK_SAFETY: '/prescriptions/check-safety/',
  },
  REVIEWS: {
    LIST: '/reviews/',
    DETAIL: (id: string) => `/reviews/${id}/`,
    DOCTOR: (doctorId: string) => `/doctors/${doctorId}/reviews/`,
  },
  VITALS: {
    LIST: '/vitals/',
    DETAIL: (id: string) => `/vitals/${id}/`,
    PATIENT_HISTORY: (patientId: string) => `/patients/${patientId}/vitals/`,
  },
  MESSAGES: {
    CONVERSATIONS: '/messages/conversations/',
    THREAD: (userId: string) => `/messages/${userId}/`,
    SEND: '/messages/',
    MARK_READ: (userId: string) => `/messages/${userId}/read/`,
    UNREAD_COUNT: '/messages/unread-count/',
  },
  AUDIT_LOGS: {
    LIST: '/admin/audit-logs/',
  },
  UPLOAD: {
    AVATAR: '/auth/avatar/',
    IMAGE: '/upload/image/',
    DELETE: '/upload/delete/',
  },
} as const;
